-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/WikiMirror/schema/json/abstractSchemaChanges/patch-remote_page_drop_updated.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/remote_page
  DROP rp_updated;
