-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/WikiMirror/schema/json/remote_page.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/remote_page (
  rp_id INT UNSIGNED NOT NULL,
  rp_namespace INT NOT NULL,
  rp_title VARBINARY(255) NOT NULL,
  rp_updated BINARY(14) NOT NULL,
  UNIQUE INDEX rp_ns_title (rp_namespace, rp_title),
  PRIMARY KEY(rp_id)
) /*$wgDBTableOptions*/;
